baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "Project Calavera"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[imaging]
quality = 75
